In [17]:
import pandas as pd
drinks = pd.read_csv("drinks.csv")
drinks
drinks.sort_values(by="beer_servings", ascending=False)

,country,beer_servings,spirit_servings,wine_servings,total_litres_of_pure_alcohol,continent
117,Namibia,376,3,1,6.8,AF
45,Czech Republic,361,170,134,11.8,EU
62,Gabon,347,98,59,8.9,AF
65,Germany,346,117,175,11.3,EU
98,Lithuania,343,244,56,12.9,EU
135,Poland,343,215,56,10.9,EU
188,Venezuela,333,100,3,7.7,SA
81,Ireland,313,118,165,11.4,EU
129,Palau,306,63,23,6.9,OC
140,Romania,297,122,167,10.4,EU
16,Belgium,295,84,212,10.5,EU
130,Panama,285,104,18,7.2,NaN
160,Spain,284,157,112,10.0,EU
151,Serbia,283,131,127,9.6,EU
93,Latvia,281,216,62,10.5,EU
9,Austria,279,75,191,9.7,EU
156,Slovenia,270,51,276,10.6,EU
60,Finland,263,133,97,10.0,EU
17,Belize,263,114,8,6.8,NaN
8,Australia,261,72,212,10.4,OC
120,Netherlands,251,88,190,9.4,EU
184,USA,249,158,84,8.7,NaN
141,Russian Federation,247,326,73,11.5,AS
3,Andorra,245,138,312,12.4,EU
23,Brazil,245,145,16,7.2,SA
32,Canada,240,122,100,8.2,NaN
109,Mexico,238,68,5,5.5,NaN
99,Luxembourg,236,133,271,11.4,EU
75,Hungary,234,215,185,11.3,EU
76,Iceland,233,61,78,6.6,EU
...,...,...,...,...,...,...
178,Tuvalu,6,41,9,1.0,OC
53,Egypt,6,4,1,0.2,AF
86,Jordan,6,21,1,0.5,AS
190,Yemen,6,0,0,0.1,AS
104,Mali,5,1,1,0.6,AF
167,Syria,5,35,16,1.0,AS
78,Indonesia,5,1,0,0.1,AS
119,Nepal,5,6,0,0.2,AS
116,Myanmar,5,1,0,0.1,AS
123,Niger,3,2,1,0.1,AF
168,Tajikistan,2,15,0,0.3,AS
171,Timor-Leste,1,1,4,0.1,AS
137,Qatar,1,42,7,0.9,AS
73,Haiti,1,326,1,5.9,NaN
38,Comoros,1,3,1,0.1,AF
46,North Korea,0,0,0,0.0,AS
40,Cook Islands,0,254,74,5.9,OC
13,Bangladesh,0,0,0,0.0,AS
147,San Marino,0,0,0,0.0,EU
90,Kuwait,0,0,0,0.0,AS
79,Iran,0,0,0,0.0,AS
149,Saudi Arabia,0,5,0,0.1,AS
97,Libya,0,0,0,0.0,AF
103,Maldives,0,0,0,0.0,AS
106,Marshall Islands,0,0,0,0.0,OC
107,Mauritania,0,0,0,0.0,AF
158,Somalia,0,0,0,0.0,AF
111,Monaco,0,0,0,0.0,EU
128,Pakistan,0,0,0,0.0,AS
0,Afghanistan,0,0,0,0.0,AS

["click here"]("www.google.com")